name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.mijoc388 }}
          password: ${{ secrets.W@b@g@h$!7600 }}

      - name: Build and push Docker image
        run: |
          docker build -t your-docker-image:latest .
          docker push your-docker-image:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Apply Kubernetes deployment
        run: kubectl apply -f kubernetes/deployment.yaml

      - name: Get the status of the pods
        run: kubectl get pods
